name: 'Inputs CodeSniffer'
description: 'Configuración inputs codeSniffer' 

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for phpcs-wordpress ###
  phpcs_args:
    description: 'Additional PHPCS flags'
    default: '.'
  phpcbf_args:
    description: 'Additional PHPCBF flags'
    default: '.'
  phpcs_standard:
    description: 'Coding standard for PHPCS to use when checking files'
    default: 'WordPress'
  use_default_configuration_file:
    description: 'Whether to use default configuration file(phpcs.xml) or not'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node-version }}'