name: WPCS checker
on: 
  push:
        inputs:
            workdir:
                description: 'Working directory relative to the root directory.'
                default: '.'
            ### Flags for phpcs-wordpress ###
            phpcs_args:
                description: 'Additional PHPCS flags'
                default: '.'
            phpcbf_args:
                description: 'Additional PHPCBF flags'
                default: '.'
            phpcs_standard:
                description: 'Coding standard for PHPCS to use when checking files'
                default: 'WordPress'
            use_default_configuration_file:
                description: 'Whether to use default configuration file(phpcs.xml) or not'
                default: 'true'
jobs:
  linter_name:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shalior/wordpress-phpcs-action@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: true
          phpcs_args: '-n' # ignore warnings
      - uses: stefanzweifel/git-auto-commit-action@v4 # auto commit the fixes action for GitHub
        with:
          commit_message: Fix PHPCS errors
